/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'
import { Route as AppProtectedRouteRouteImport } from './routes/_app/_protected/route'
import { Route as AppArticlesArticleIdRouteImport } from './routes/_app/articles.$articleId'
import { Route as AppProtectedEditorRouteImport } from './routes/_app/_protected/editor'
import { Route as AppProtectedAccountSettingsRouteImport } from './routes/_app/_protected/account/settings'
import { Route as AppProtectedAccountSecurityRouteImport } from './routes/_app/_protected/account/security'
import { Route as AppProtectedArticlesEditArticleIdRouteImport } from './routes/_app/_protected/articles.edit.$articleId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtectedRouteRoute = AppProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArticlesArticleIdRoute = AppArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProtectedEditorRoute = AppProtectedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppProtectedRouteRoute,
} as any)
const AppProtectedAccountSettingsRoute =
  AppProtectedAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => AppProtectedRouteRoute,
  } as any)
const AppProtectedAccountSecurityRoute =
  AppProtectedAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AppProtectedRouteRoute,
  } as any)
const AppProtectedArticlesEditArticleIdRoute =
  AppProtectedArticlesEditArticleIdRouteImport.update({
    id: '/articles/edit/$articleId',
    path: '/articles/edit/$articleId',
    getParentRoute: () => AppProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/editor': typeof AppProtectedEditorRoute
  '/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/account/security': typeof AppProtectedAccountSecurityRoute
  '/account/settings': typeof AppProtectedAccountSettingsRoute
  '/articles/edit/$articleId': typeof AppProtectedArticlesEditArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/editor': typeof AppProtectedEditorRoute
  '/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/account/security': typeof AppProtectedAccountSecurityRoute
  '/account/settings': typeof AppProtectedAccountSettingsRoute
  '/articles/edit/$articleId': typeof AppProtectedArticlesEditArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_protected': typeof AppProtectedRouteRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_protected/editor': typeof AppProtectedEditorRoute
  '/_app/articles/$articleId': typeof AppArticlesArticleIdRoute
  '/_app/_protected/account/security': typeof AppProtectedAccountSecurityRoute
  '/_app/_protected/account/settings': typeof AppProtectedAccountSettingsRoute
  '/_app/_protected/articles/edit/$articleId': typeof AppProtectedArticlesEditArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/$pathname'
    | '/auth/verify-email'
    | '/editor'
    | '/articles/$articleId'
    | '/account/security'
    | '/account/settings'
    | '/articles/edit/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/$pathname'
    | '/auth/verify-email'
    | '/editor'
    | '/articles/$articleId'
    | '/account/security'
    | '/account/settings'
    | '/articles/edit/$articleId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_protected'
    | '/auth/$pathname'
    | '/auth/verify-email'
    | '/_app/'
    | '/_app/_protected/editor'
    | '/_app/articles/$articleId'
    | '/_app/_protected/account/security'
    | '/_app/_protected/account/settings'
    | '/_app/_protected/articles/edit/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthPathnameRoute: typeof AuthPathnameRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppProtectedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/articles/$articleId': {
      id: '/_app/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof AppArticlesArticleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_protected/editor': {
      id: '/_app/_protected/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AppProtectedEditorRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/account/settings': {
      id: '/_app/_protected/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AppProtectedAccountSettingsRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/account/security': {
      id: '/_app/_protected/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AppProtectedAccountSecurityRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
    '/_app/_protected/articles/edit/$articleId': {
      id: '/_app/_protected/articles/edit/$articleId'
      path: '/articles/edit/$articleId'
      fullPath: '/articles/edit/$articleId'
      preLoaderRoute: typeof AppProtectedArticlesEditArticleIdRouteImport
      parentRoute: typeof AppProtectedRouteRoute
    }
  }
}

interface AppProtectedRouteRouteChildren {
  AppProtectedEditorRoute: typeof AppProtectedEditorRoute
  AppProtectedAccountSecurityRoute: typeof AppProtectedAccountSecurityRoute
  AppProtectedAccountSettingsRoute: typeof AppProtectedAccountSettingsRoute
  AppProtectedArticlesEditArticleIdRoute: typeof AppProtectedArticlesEditArticleIdRoute
}

const AppProtectedRouteRouteChildren: AppProtectedRouteRouteChildren = {
  AppProtectedEditorRoute: AppProtectedEditorRoute,
  AppProtectedAccountSecurityRoute: AppProtectedAccountSecurityRoute,
  AppProtectedAccountSettingsRoute: AppProtectedAccountSettingsRoute,
  AppProtectedArticlesEditArticleIdRoute:
    AppProtectedArticlesEditArticleIdRoute,
}

const AppProtectedRouteRouteWithChildren =
  AppProtectedRouteRoute._addFileChildren(AppProtectedRouteRouteChildren)

interface AppRouteRouteChildren {
  AppProtectedRouteRoute: typeof AppProtectedRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppArticlesArticleIdRoute: typeof AppArticlesArticleIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProtectedRouteRoute: AppProtectedRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppArticlesArticleIdRoute: AppArticlesArticleIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthPathnameRoute: AuthPathnameRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
